### ISSUE TITLE
pdb activates when parsing

### ISSUE THREAD

**Issue by butsugiri** [c-amr/camr#10]
I am having an issue with parsing.
When I run `python amr_parsing.py -m parse` command, the `pdb` activates and the parser stops running.
I am using the HEAD version of the CAMR and `stanford-corenlp-full-2015-04-20`.

I did preprocessing by `python amr_parsing.py -m preprocess sample.txt`,
where `sample.txt` contains single sentence: "australian current account deficit narrows sharply".

I think that preprocessing is done correctly (files generated by preprocessing weren't empty).

I tried 1a52d91080fccdd117079a2bdf080ed4e4e49966 and the parsing actually worked. Thus I think that this is the issue of the HEAD version.

**Comment by Juicechuan** [comment]
Thank you so much for bringing this up. There is a bug when reading in the preprocessing result. Now it should be working.

**Comment by butsugiri** [comment]
Thank you for your quick response.
I used the latest commit and confirmed that the issue has been solved.
