### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by mdtux89** [c-amr/camr#2]
Hi, is there a way to train the parser on a different dataset?
Thanks,
Marco

**Comment by Juicechuan** [comment]
Yes. You could train the parser using the following command:
`python amr_parsing.py -m train --model path_to_save_model --iter N [-d path_to_amr_dev_file] --amrfmt path_to_amr_training_file > log/train.log`

But before you start training the parser, make sure you get all the preprocess files and the aligned amr file ready.

Chuan

**Comment by mdtux89** [comment]
Thanks!

**Comment by mdtux89** [comment]
For preprocess files you mean running this 
` python amr_parsing.py -m preprocess [input_sentence_file]`
on the data, right?

**Comment by Juicechuan** [comment]
Yes.

**Comment by mdtux89** [comment]
Hi Chuan, I can't save the trained model because of this exception (which is raised in model.py at line 338): Saving model error <type 'exceptions.ValueError'>

Do you have any idea of what causes this problem?

Marco

**Comment by Kamoleon** [comment]
Has anyone found a solution to the saving model error?

**Comment by mdtux89** [comment]
From what I could gather, it's a python bug that is fixed only in python 3.0. 

http://bugs.python.org/issue11564

They were discussing it here too: https://github.com/numpy/numpy/issues/2396

**Comment by Juicechuan** [comment]
I've updated the parser to the newest version, which should not have saving model error. The problem is python2's bug, however it turns out the initial shape of the weight matrix is too big and the current version use a small initial parameter

**Comment by IceIceRabbit** [comment]
Thanks for the update

**Comment by IceIceRabbit** [comment]
Hey would it be possible to update the readme?

**Comment by Juicechuan** [comment]
@IceIceRabbit Hi, I've update the readme, feel free to comment for further problems.
