### ISSUE TITLE
Preprocessing data

### ISSUE THREAD

**Issue by kexinliao** [c-amr/camr#4]
Hi there,

I got empty outputs after running the preprocessing command:
python amr_parsing.py -m preprocess [input_sentence_file](My input sentence file was raw document with one sentence per line.)
This generated .tok, .prp and .charniak.parse.dep files, but all of them were just empty.
Anyone can help with this issue? 

Log info: 
Start Stanford CoreNLP...
java -Xmx2500m -cp stanfordnlp/stanford-corenlp-full-2013-06-20/stanford-corenlp-3.2.0.jar:stanfordnlp/stanford-corenlp-full-2013-06-20/stanford-corenlp-3.2.0-models.jar:stanfordnlp/stanford-corenlp-full-2013-06-20/joda-time.jar:stanfordnlp/stanford-corenlp-full-2013-06-20/xom.jar:stanfordnlp/stanford-corenlp-full-2013-06-20/jollyday.jar edu.stanford.nlp.pipeline.StanfordCoreNLP -props stanfordnlp/default.properties
Loading Models: 0/4  
Loading Models: 1/4  
Loading Models: 2/4  
Loading Models: 3/4  
Loading Models: 4/4  
Read token,lemma,name entity file test_input.txt.sent.prp...
Loading Charniak parser model: WSJ+Gigaword ...
Begin Charniak parsing ...
Convert Charniak parse tree to Stanford Dependency tree ...
Read dependency file test_input.txt.sent.tok.charniak.parse.dep...
Done preprocessing!

**Comment by IceIceRabbit** [comment]
Make  a copy of the sentence file and rename it the same with the .txt.sent extension it should work provided your sentences file is only sentences

**Comment by Juicechuan** [comment]
Hi, try removing all the old empty file and re-run it again, the parser did this cache thing and will not overwrite the file if it is there.

**Comment by kexinliao** [comment]
So my input file in the command should be the original file name or file
name with .sent extension?

**Comment by IceIceRabbit** [comment]
your original file , you .sent file should have all the sentences extracted from the original file.
If the original file is only sentences you can just copy it and rename it with .sent extension from what I have understood.

**Comment by kexinliao** [comment]
@IceIceRabbit Thanks! Finally I'm able to preprocess the sentence file. 
Now I got the following error when parsing the sentence file to amr. 

Traceback (most recent call last):
  File "amr_parsing.py", line 439, in <module>
    main()
  File "amr_parsing.py", line 390, in main
    if args.section != 'all':
  File "/home/kexin/AMRParsing/model.py", line 352, in load_model
    model = pickle.load(f)
cPickle.UnpicklingError: invalid load key, 'B'.

The pre-trained model 'LDC2013E117.train.basic-abt-charniak.m' was downloaded from the link in the readme file.

**Comment by IceIceRabbit** [comment]
yeah, there seems to be problem with the old model,I believe that was trained on the parser before its latest update , you can try to train your own model that should work.

**Comment by kexinliao** [comment]
@Juicechuan Hi Chuan, 
Could you provide us a pre-trained model which is trained on the updated parser?

**Comment by Juicechuan** [comment]
@kexinliao Hi I've uploaded the new model (there is still some problem with the semeval model, but I should be able to upload it recently). Let me know if there is any question or problem.

**Comment by kexinliao** [comment]
@Juicechuan Thanks! It works now.
