### ISSUE TITLE
Invalid link to model SemEval2016 

### ISSUE THREAD

**Issue by WolfNiu** [c-amr/camr#8]
Two models were provided in the readme file, and yet the SemEval2016 one points to an invalid link.

Thanks,

Best,

Tong

**Comment by boudinfl** [comment]
same problem here, the download link for the semeval-2016 model (http://www.cs.brandeis.edu/%7Ecwang24/files/amr-semeval-all.train.m.tar.gz) is invalid.

**Comment by Juicechuan** [comment]
Thanks for the reminding. It should be working now.

**Comment by WolfNiu** [comment]
Thank you for the update!

Best,

Tong

On Mar 16, 2017, at 11:51, Chuan Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the reminding. It should be working now.
